name: RealisticVillagers
version: ${project.parent.version}
author: Matsubara
main: me.matsubara.realisticvillagers.RealisticVillagers
api-version: 1.18
load: STARTUP
description: ${project.description}
depend:
  - packetevents
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - MarriageMaster

commands:
  realisticvillagers:
    description: main command.
    usage: /<command>
    aliases:
      - rv
      - rvillagers
      - realvillagers