# This is a basic workflow to help you get started with Actions 
 name: RealisticVillagers Builder 
 # Controls when the action will run. Triggers the workflow on push or pull request 
 # events but only for the master branch 
 on: 
   workflow_dispatch: 
     inputs: 
       logLevel: 
         description: 'Log level' 
         required: true 
         default: 'warning' 
       tags: 
         description: 'Test scenario tags' 
   push: 
     branches: [ "master" ] 
   pull_request: 
     branches: [ "master" ] 
  
 jobs: 
   build:
     permissions: write-all 
     runs-on: ubuntu-latest 
     steps: 
     - uses: actions/checkout@v3 
     - name: Set up JDK 17 
       uses: actions/setup-java@v3 
       with: 
         java-version: '17' 
         distribution: 'temurin' 
         server-id: phoenixdevt-releases 
     - name: Set up JDK 21 
       uses: actions/setup-java@v3 
       with: 
         java-version: '21' 
         distribution: 'temurin' 
         server-id: phoenixdevt-releases 
     - name: Install depends 
       run: mvn install
     - name: Build with Maven 
       run: mvn -B package --file pom.xml
     - run: mkdir staging && cp target/*.jar staging 
     - name: Set Release version env variable 
       run: | 
         echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV 
     - name: "Build & test" 
       run: | 
         echo "done!" 
     - uses: "marvinpinto/action-automatic-releases@latest" 
       with: 
         repo_token: "${{ secrets.GITHUB_TOKEN }}" 
         automatic_release_tag: "${{ env.RELEASE_VERSION }}" 
         prerelease: false 
         title: "Release ${{ env.RELEASE_VERSION }}" 
         files: | 
           staging/*.jar
